lib/montacargas_web/router.ex
defmodule MontaCargasWeb.Router do
  use MontaCargasWeb, :router

  pipeline :auth do
    plug(Guardian.Plug.Pipeline,
      module: MontaCargasWeb.Guardian,
      error_handler: MontaCargasWeb.Guardian.ErrorHandler
    )

    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.VerifyHeader)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/login", MontaCargasWeb do
    pipe_through([:browser, :auth])

    get("/", LoginController, :index)
  end

  scope "/", MontaCargasWeb do
    pipe_through([:browser, :auth, :ensure_auth])

    get("/", PageController, :index)
  end

  scope "/auth", MontaCargasWeb do
    pipe_through([:browser])

    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :callback)
    post("/:provider/callback", AuthController, :callback)
    delete("/logout", AuthController, :delete)
  end
end

lib/montacargas/application.ex
defmodule MontaCargas.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(MontaCargas.Repo, []),
      # Start the endpoint when the application starts
      supervisor(MontaCargasWeb.Endpoint, [])
      # Start your own worker by calling: MontaCargas.Worker.start_link(arg1, arg2, arg3)
      # worker(MontaCargas.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: MontaCargas.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    MontaCargasWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/montacargas/repo.ex
defmodule MontaCargas.Repo do
  use Ecto.Repo, otp_app: :montacargas

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/montacargas_web/controllers/auth_controller.ex
defmodule MontaCargasWeb.AuthController do
  alias MontaCargasWeb.Models

  @moduledoc """
  Auth controller responsible for handling Ueberauth responses
  """

  use MontaCargasWeb, :controller
  plug(Ueberauth)

  alias Ueberauth.Strategy.Helpers

  def request(conn, _params) do
    render(conn, "request.html", callback_url: Helpers.callback_url(conn))
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "You have been logged out!")
    |> configure_session(drop: true)
    |> MontaCargasWeb.Guardian.Plug.sign_out()
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_failure: _fails}} = conn, _params) do
    conn
    |> put_flash(:error, "Failed to authenticate.")
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    case Models.UserFromAuth.find_or_create(auth) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Signed in as #{user.name}")
        |> MontaCargasWeb.Guardian.Plug.sign_in(user)
        |> put_session(:current_user, user)
        |> redirect(to: page_path(conn, :index))

      {:error, reason} ->
        conn
        |> put_flash(:error, reason)
        |> redirect(to: "/")
    end
  end
end

lib/montacargas_web/controllers/login_controller.ex
defmodule MontaCargasWeb.LoginController do
  use MontaCargasWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html", layout: {MontaCargasWeb.LayoutView, "login.html"})
  end
end

lib/montacargas_web/controllers/page_controller.ex
defmodule MontaCargasWeb.PageController do
  use MontaCargasWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html", current_user: get_session(conn, :current_user))
  end
end

lib/montacargas_web/views/error_view.ex
defmodule MontaCargasWeb.ErrorView do
  use MontaCargasWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/montacargas_web/views/layout_view.ex
defmodule MontaCargasWeb.LayoutView do
  use MontaCargasWeb, :view
end

lib/montacargas_web/views/login_view.ex
defmodule MontaCargasWeb.LoginView do
  use MontaCargasWeb, :view
end

lib/montacargas_web/views/page_view.ex
defmodule MontaCargasWeb.PageView do
  use MontaCargasWeb, :view
end

lib/montacargas_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Hello MontaCargas!</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/font-awesome.min.css") %>">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/tabler-ui.css") %>">
  <script src="<%= static_path(@conn, "/js/app.js") %>
  ">
  </script>
</head>

<body class="">
  <div class="page">
    <div class="page-main">
      <div class="header py-4">
        <div class="container">
          <div class="d-flex">
            <a class="header-brand" href="./">
                <img src="<%= static_path(@conn, "/images/forklift.png") %>" class="header-brand-img" alt="Monta Cargas">
                Monta Cargas
              </a>
            <div class="d-flex order-lg-2 ml-auto">
              <div class="dropdown">
                <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
                    <span class="avatar" style="background-image: url(<%= @current_user.avatar %>)"></span>
                    <span class="ml-2 d-none d-lg-block">
                      <span class="text-default"><%= @current_user.name %></span>
                    </span>
                  </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                  <a class="dropdown-item" href="#">
                      <i class="dropdown-icon fe fe-user"></i> Profile
                    </a>
                  <div class="dropdown-divider"></div>
                  <%= link to: auth_path(@conn, :delete), method: :delete, class: "dropdown-item" do %>
                  <i class="dropdown-icon fe fe-log-out"></i> Sign out
                  <% end %>
                </div>
              </div>
            </div>
            <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                <span class="header-toggler-icon"></span>
              </a>
          </div>
        </div>
      </div>
      <div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-3 ml-auto">
            </div>
            <div class="col-lg order-lg-first">
              <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                <li class="nav-item">
                  <a href="./index.html" class="nav-link"><i class="fe fe-home"></i> Home</a>
                </li>
                <li class="nav-item">
                  <a href="./index.html" class="nav-link"><i class="fe fe-activity"></i> Jobs</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

lib/montacargas_web/templates/layout/login.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Hello MontaCargas!</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/font-awesome.min.css") %>">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/tabler-ui.css") %>">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
</head>

<body>
  <%= render @view_module, @view_template, assigns %>
</body>

</html>

lib/montacargas_web/templates/login/index.html.eex
<div class="page">
  <div class="page-single">
    <div class="container">
      <div class="row">
        <div class="col col-login mx-auto">
          <form class="card" action="" method="post">
            <div class="card-body p-6">
              <div class="card-title">Login to your account</div>
              <div class="form-footer">
                <a class="btn btn-block btn-danger" href="/auth/google">Sign in with Google</a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

lib/montacargas_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Überauth + Phoenix Example</h2>
  <p class="lead">
  This is an application to show an example of how to wire up
  <a href="https://github.com/ueberauth/ueberauth">Überauth</a> with
  <a href="https://github.com/phoenixframework/phoenix">Phoenix</a>.
  </p>

  <%= if @current_user do %>
    <h2>Welcome, <%= @current_user.name %>!</h2>
    <img src="<%= @current_user.avatar %>" class="img-circle"/>
    <%= button "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn btn-danger" %>
    <br>
  <% else %>
    <a class="btn btn-primary btn-lg" href="/auth/google">
      <i class="fa fa-google"></i>
      Sign in with Google
    </a>
  <% end %>
</div>